'use client';

import { useState } from 'react';

type AnalysisResult = {
  summary: string;
  score: number;
  strengths: string[];
  improvements: string[];
};

// Bedrock sometimes wraps the JSON in a ```json ... ``` code fence — strip it before parsing.
function parseAnalysis(raw: string): AnalysisResult | null {
  try {
    const cleaned = raw.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '');
    const parsed = JSON.parse(cleaned);
    if (
      typeof parsed.summary === 'string' &&
      typeof parsed.score === 'number' &&
      Array.isArray(parsed.strengths) &&
      Array.isArray(parsed.improvements)
    ) {
      return parsed;
    }
    return null;
  } catch {
    return null;
  }
}

function scoreColor(score: number) {
  if (score >= 80) return { ring: '#34d399', text: 'text-emerald-400', bg: 'bg-emerald-500/10' };
  if (score >= 60) return { ring: '#fbbf24', text: 'text-amber-400', bg: 'bg-amber-500/10' };
  return { ring: '#f87171', text: 'text-red-400', bg: 'bg-red-500/10' };
}

function ScoreGauge({ score }: { score: number }) {
  const { ring, text } = scoreColor(score);
  const radius = 42;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference * (1 - score / 100);

  return (
    <div className="relative h-28 w-28 shrink-0">
      <svg viewBox="0 0 100 100" className="h-28 w-28 -rotate-90">
        <circle cx="50" cy="50" r={radius} stroke="#1e293b" strokeWidth="8" fill="none" />
        <circle
          cx="50"
          cy="50"
          r={radius}
          stroke={ring}
          strokeWidth="8"
          fill="none"
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          style={{ transition: 'stroke-dashoffset 0.6s ease' }}
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className={`text-2xl font-extrabold ${text}`}>{score}</span>
        <span className="text-[10px] text-slate-500 tracking-wide">/ 100</span>
      </div>
    </div>
  );
}

function stripCritical(text: string) {
  const match = text.match(/^\s*CRITICAL:?\s*/i);
  return { critical: !!match, text: match ? text.slice(match[0].length) : text };
}

function AnalysisReport({ result }: { result: AnalysisResult }) {
  const { text: scoreText, bg } = scoreColor(result.score);

  return (
    <div className="space-y-6">
      <div className={`flex items-center gap-5 rounded-xl border border-slate-800 p-5 ${bg}`}>
        <ScoreGauge score={result.score} />
        <div>
          <div className={`text-xs font-semibold uppercase tracking-wider ${scoreText}`}>Overall Score</div>
          <p className="mt-1 text-sm leading-relaxed text-slate-300">{result.summary}</p>
        </div>
      </div>

      <div>
        <h3 className="mb-3 flex items-center gap-2 text-sm font-bold uppercase tracking-wide text-emerald-400">
          <span className="flex h-2 w-2 rounded-full bg-emerald-400" />
          Strengths
        </h3>
        <ul className="space-y-2">
          {result.strengths.map((s, i) => (
            <li key={i} className="flex gap-2 text-sm leading-relaxed text-slate-300">
              <span className="mt-0.5 shrink-0 text-emerald-400">✓</span>
              <span>{s}</span>
            </li>
          ))}
        </ul>
      </div>

      <div>
        <h3 className="mb-3 flex items-center gap-2 text-sm font-bold uppercase tracking-wide text-amber-400">
          <span className="flex h-2 w-2 rounded-full bg-amber-400" />
          Suggested Improvements
        </h3>
        <ul className="space-y-2">
          {result.improvements.map((raw, i) => {
            const { critical, text } = stripCritical(raw);
            return (
              <li key={i} className="flex gap-2 text-sm leading-relaxed text-slate-300">
                <span className="mt-0.5 shrink-0 text-amber-400">→</span>
                <span>
                  {critical && (
                    <span className="mr-2 rounded-full bg-red-500/15 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-red-400">
                      Critical
                    </span>
                  )}
                  {text}
                </span>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
}

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const [statusMessage, setStatusMessage] = useState('');
  const [aiResult, setAiResult] = useState<string | null>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setFile(e.target.files[0]);
      setAiResult(null);
      setStatusMessage(`Selected file: ${e.target.files[0].name}`);
    }
  };

  // Poll DynamoDB to fetch the real AI analysis result generated by Lambda
  const pollDynamoDB = async (applicationId: string) => {
    const maxAttempts = 35; // Maximum 35 attempts (approx. 105 seconds)
    let attempts = 0;

    const interval = setInterval(async () => {
      attempts++;
      try {
        const res = await fetch(`/api/get-analysis?applicationId=${encodeURIComponent(applicationId)}`);
        if (!res.ok) return;
        
        const data = await res.json();

        if (data.status === 'COMPLETED' && data.analysis_result) {
          clearInterval(interval);
          setAiResult(data.analysis_result);
          setIsUploading(false);
          setStatusMessage('Analysis complete! Results fetched directly from Amazon DynamoDB.');
        } else if (attempts >= maxAttempts) {
          clearInterval(interval);
          setIsUploading(false);
          setStatusMessage('Analysis timed out. Please check AWS CloudWatch logs.');
        }
      } catch (err) {
        console.error('Polling error:', err);
      }
    }, 3000); // Poll every 3 seconds
  };

  const handleUploadAndAnalyze = async () => {
    if (!file) {
      alert('Please select a PDF resume first!');
      return;
    }

    setIsUploading(true);
    setStatusMessage('1. Requesting secure presigned upload URL from AWS...');

    try {
      const res = await fetch('/api/get-presigned-url', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ filename: file.name, filetype: file.type }),
      });
      
      if (!res.ok) throw new Error('Failed to retrieve presigned URL');
      // Extract both uploadUrl and objectKey from the API response
      const { uploadUrl, objectKey } = await res.json();

      setStatusMessage('2. Channel established. Uploading resume directly to Amazon S3...');

      const uploadRes = await fetch(uploadUrl, {
        method: 'PUT',
        headers: { 'Content-Type': file.type },
        body: file,
      });

      if (!uploadRes.ok) throw new Error('Failed to upload file to S3');

      // Generate the exact application_id used in Lambda: objectKey with '/' replaced by '_'
      const applicationId = objectKey.replace(/\//g, '_');

      setStatusMessage('3. Upload successful! SQS -> Lambda -> Bedrock pipeline running. Polling DynamoDB...');
      
      // Start polling DynamoDB for the real result instead of using setTimeout
      pollDynamoDB(applicationId);

    } catch (error) {
      console.error(error);
      setStatusMessage('An error occurred. Please check your AWS credentials or local configuration.');
      setIsUploading(false);
    }
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-center bg-slate-950 p-6 text-white">
      <div className="text-center mb-10">
        <h1 className="text-4xl font-extrabold tracking-tight bg-gradient-to-r from-blue-400 via-indigo-400 to-purple-500 bg-clip-text text-transparent">
          AWS Agentic Job Assistant
        </h1>
        <p className="mt-2 text-slate-400 text-sm">
          Enterprise-grade AWS serverless decoupled architecture for AI-powered resume auditing.
        </p>
      </div>

      <div className="w-full max-w-2xl bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl">
        <div className="border-2 border-dashed border-slate-700 hover:border-indigo-500 rounded-xl p-8 text-center cursor-pointer transition relative bg-slate-950/50">
          <input 
            type="file" 
            accept=".pdf"
            onChange={handleFileChange}
            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
          />
          <p className="text-slate-300 font-medium">Click or drag & drop your PDF resume here</p>
          <p className="text-slate-500 text-xs mt-1">Standard PDF format files only</p>
        </div>

        {statusMessage && (
          <div className="mt-4 text-sm text-indigo-400 font-mono text-center">
            {statusMessage}
          </div>
        )}

        <button
          onClick={handleUploadAndAnalyze}
          disabled={isUploading}
          className={`w-full mt-6 py-3 px-4 rounded-xl font-bold transition-all text-white ${
            isUploading 
              ? 'bg-slate-800 text-slate-500 cursor-not-allowed' 
              : 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 shadow-lg shadow-indigo-500/20'
          }`}
        >
          {isUploading ? 'Agent is thinking...' : 'Start AI Smart Audit'}
        </button>
      </div>

      {aiResult && (
        <div className="w-full max-w-2xl mt-8 bg-slate-900 border border-emerald-900/30 rounded-2xl p-8 shadow-2xl">
          <div className="text-emerald-400 font-bold mb-5 flex items-center gap-2 text-sm uppercase tracking-wide">
            <span className="flex h-2 w-2 rounded-full bg-emerald-400 animate-pulse" />
            AI Analysis Report
          </div>
          {(() => {
            const parsed = parseAnalysis(aiResult);
            return parsed ? (
              <AnalysisReport result={parsed} />
            ) : (
              <div className="text-slate-300 whitespace-pre-wrap font-sans leading-relaxed text-sm bg-slate-950 p-4 rounded-xl border border-slate-800">
                {aiResult}
              </div>
            );
          })()}
        </div>
      )}
    </main>
  );
}